spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    generate-ddl: true
  datasource:
    url: jdbc:postgresql://localhost:5432/spock
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  main:
    allow-bean-definition-overriding: true

  jackson:
    serialization:
      fail-on-empty-beans: false

server:
  port: 8081
